version: '2'
services:
    master:
        build: .
        command: bash -c "source /opt/ros/melodic/setup.bash && roscore"
        container_name: master
    bridge:
        build: .
        container_name: bridge
